/*
 * Copyright (c) Dotted Eyes Ltd 2018.
 * All Rights Reserved.
 *
 * This Software is the confidential information of
 * Dotted Eyes Ltd. 67-71 Northwood St,
 * Birmingham, B3 1TX, United Kingdom.
 *
 * The software may be used only in accordance with the terms
 * of the licence agreement made with Dotted Eyes Ltd.
 *
 */
package lib.models.bots;

import lib.hlt.Command;
import lib.hlt.Constants;
import lib.hlt.Ship;
import lib.models.ships.StatefulShip;
import lib.navigation.NavigationManager;

import java.util.ArrayList;

public class StatefulBot extends AbstractBot<StatefulShip> {

    private static StatefulBot INSTANCE;

    private NavigationManager navigationManager = new NavigationManager();

    public static StatefulBot getInstance() {
        if (INSTANCE == null) {
            INSTANCE = new StatefulBot();
        }

        return INSTANCE;
    }

    @Override
    protected void onTurnStart() {
        navigationManager.onTurnStart(game);
    }

    @Override
    protected void onTurnEnd() {

    }

    @Override
    protected void onGameStart() {

    }

    @Override
    protected void onGameEnd() {

    }

    @Override
    protected ArrayList<Command> getCommandQueue() {

        for (final StatefulShip ship : ships.values()) {
            ship.updateState(game);
        }

        final ArrayList<Command> commandQueue = new ArrayList<>(navigationManager.resolveShipDirections(ships.values(), game.gameMap));

        // TODO: manage bot-level updates better - use states for this too?
        if (
                game.turnNumber <= 200 &&
                        game.me.halite >= Constants.SHIP_COST &&
                        !game.gameMap.at(game.me.shipyard).isOccupied() &&
                        // TODO don't check isOccupied, check against our list of occupied positions thats generated by resolveDirectionScores()
                        !navigationManager.getOccupiedPositions().contains(game.gameMap.at(game.me.shipyard).position))
        {
            commandQueue.add(game.me.shipyard.spawn());

            // Tell that navigation manager that we are spawning a ship
            navigationManager.markOccupied(game.me.shipyard.position);
        }

        return commandQueue;
    }

    @Override
    protected StatefulShip createShip(Ship initialStatus) {
        return new StatefulShip(initialStatus);
    }
}
